[build.env]
passthrough = [
    "CARGO_NET_GIT_FETCH_WITH_CLI",
    "GIT_TERMINAL_PROMPT"
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install -y cmake pkg-config libdbus-1-dev:$CROSS_DEB_ARCH libssl-dev:$CROSS_DEB_ARCH perl git",
    "git config --global credential.helper ''",
    "git config --global url.'https://'.insteadOf git://"
]
